set local check_function_bodies = off;

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

create table "public"."blocks" (
  "id"         bigint                   generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "data"       jsonb                    not null,
  "position_x" integer                  not null default 0,
  "position_y" integer                  not null default 0,
  "layer"      integer                  not null default 0,
  constraint "blocks_pkey" primary key (id)
);

alter table "public"."blocks"
  enable row level security;

create table "public"."roles" (
  "id"          text not null,
  "description" text not null,
  constraint "roles_pkey" primary key (id)
);

alter table "public"."roles"
  enable row level security;

create table "public"."transitions" (
  "id"            bigint                   generated by default as identity not null,
  "created_at"    timestamp with time zone not null default now(),
  "updated_at"    timestamp with time zone not null default now(),
  "from_block_id" bigint                   not null,
  "to_block_id"   bigint                   not null,
  "from_floor"    integer                  not null,
  "from_position" text                     not null,
  "to_floor"      integer                  not null,
  "to_position"   text                     not null,
  constraint "transitions_pkey" primary key (id)
);

alter table "public"."transitions"
  enable row level security;

create table "public"."user_roles" (
  "user_id"    uuid                     not null,
  "role_id"    text                     not null,
  "granted_by" uuid,
  "granted_at" timestamp with time zone not null default now(),
  "expires_at" timestamp with time zone,
  constraint "user_roles_pkey" primary key (user_id, role_id)
);

alter table "public"."user_roles"
  enable row level security;

create or replace function public.rls_auto_enable()
  returns event_trigger
  language plpgsql
  security definer
  set search_path to 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

alter table "public"."transitions"
  add constraint "transitions_from_block_id_fkey" foreign key (from_block_id) references public.blocks(id) on delete cascade;

alter table "public"."transitions"
  add constraint "transitions_to_block_id_fkey" foreign key (to_block_id) references public.blocks(id) on delete cascade;

alter table "public"."user_roles"
  add constraint "user_roles_granted_by_fkey" foreign key (granted_by) references auth.users(id) on delete set null;

alter table "public"."user_roles"
  add constraint "user_roles_role_id_fkey" foreign key (role_id) references public.roles(id) on delete cascade;

alter table "public"."user_roles"
  add constraint "user_roles_user_id_fkey" foreign key (user_id) references auth.users(id) on delete cascade;

create index idx_blocks_pos on public.blocks using btree (position_x, position_y, layer);

create index idx_transitions_from on public.transitions using btree (from_block_id);

create index idx_transitions_to on public.transitions using btree (to_block_id);

create index idx_user_roles_role on public.user_roles using btree (role_id);

create index idx_user_roles_user on public.user_roles using btree (user_id);

create policy "Editors can change blocks" on "public"."blocks"
  for all
  to "authenticated"
  using ((exists ( select 1
   from public.user_roles
  where ((user_roles.user_id = auth.uid()) AND (user_roles.role_id = ANY (ARRAY['editor'::text, 'admin'::text]))))))
  with check ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role_id = ANY (ARRAY['editor'::text, 'admin'::text]))))));

create policy "Enable read access for all users" on "public"."blocks"
  for select
  to PUBLIC
  using (true);

create policy "Editors can change transitions" on "public"."transitions"
  for all
  to "authenticated"
  using ((exists ( select 1
   from public.user_roles
  where ((user_roles.user_id = auth.uid()) AND (user_roles.role_id = ANY (ARRAY['editor'::text, 'admin'::text]))))))
  with check ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role_id = ANY (ARRAY['editor'::text, 'admin'::text]))))));

create policy "Enable read access for all users" on "public"."transitions"
  for select
  to PUBLIC
  using (true);

create policy "Read access for authenticated" on "public"."user_roles"
  for select
  to "authenticated"
  using (true);

create event trigger "ensure_rls"
  on ddl_command_end
  when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  execute function "public"."rls_auto_enable"();

alter publication "supabase_realtime" add table "public"."blocks";

alter publication "supabase_realtime" add table "public"."transitions";

comment on table "public"."roles" is 'Set of roles and descriptions';

grant execute on function "public"."rls_auto_enable"() to public, "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."blocks" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."roles" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."transitions" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."user_roles" to "anon", "authenticated", "postgres", "service_role";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";

