-- Comments system: table, trigger, RPCs, RLS, storage bucket.
-- Вводится роль moderator рядом с editor/admin для модерации комментариев.

-- ============ Таблица комментариев ============

create table "public"."comments" (
  "id"         bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "author_id"  uuid not null,
  "text"       text not null,
  "parent_id"  bigint,
  "root_id"    bigint,
  "block_id"   bigint,
  "map_x"      double precision,
  "map_y"      double precision,
  "layer"      integer,
  "expires_at" timestamp with time zone,
  constraint "comments_pkey" primary key (id),
  constraint "comments_author_id_fkey" foreign key (author_id) references auth.users (id) on delete cascade,
  constraint "comments_block_id_fkey" foreign key (block_id) references public.blocks (id) on delete cascade,
  constraint "comments_parent_id_fkey" foreign key (parent_id) references public.comments (id) on delete cascade,
  constraint "comments_root_id_fkey" foreign key (root_id) references public.comments (id) on delete cascade,
  constraint "comments_text_not_empty" check (char_length(text) > 0),
  constraint "comments_text_max_length" check (char_length(text) <= 2000),
  -- Комментарий привязан либо к блоку, либо к точке карты (map_x/map_y/layer), не к обоим.
  -- Ответы (parent_id задан) местоположение не наследуют и могут иметь все поля NULL.
  constraint "comments_location_check" check (
    (parent_id is not null and block_id is null and map_x is null and map_y is null and layer is null)
    or (block_id is not null and map_x is null and map_y is null and layer is null)
    or (block_id is null and map_x is not null and map_y is not null and layer is not null)
  ),
  -- Нельзя ответить самому себе.
  constraint "comments_parent_not_self" check (parent_id is distinct from id)
);

alter table "public"."comments"
  enable row level security;

-- Индексы для выборок по корню/блоку/карте
create index "idx_comments_root_id" on "public"."comments" using btree (root_id);
create index "idx_comments_parent_id" on "public"."comments" using btree (parent_id);
create index "idx_comments_block_id" on "public"."comments" using btree (block_id);
create index "idx_comments_author_id" on "public"."comments" using btree (author_id);
create index "idx_comments_map_location" on "public"."comments" using btree (layer, map_x, map_y);
create index "idx_comments_expires_at" on "public"."comments" using btree (expires_at) where (expires_at is not null);

-- ============ Триггер: проставляем root_id ============
-- AFTER INSERT, т.к. в BEFORE-триггере id identity-колонки ещё не сгенерирован.
-- SECURITY DEFINER (владелец таблицы), чтобы UPDATE прошёл в обход RLS.
create or replace function "public"."comments_set_root"()
  returns trigger
  language plpgsql
  security definer
  set search_path = 'public'
as $function$
declare
  resolved_root bigint;
begin
  if new.parent_id is null then
    resolved_root := new.id;
  else
    select coalesce(c.root_id, c.id) into resolved_root
      from public.comments c
      where c.id = new.parent_id;
    if resolved_root is null then
      resolved_root := new.parent_id;
    end if;
  end if;

  update public.comments
     set root_id = resolved_root
   where id = new.id;

  return new;
end;
$function$;

drop trigger if exists "comments_set_root_trigger" on "public"."comments";
create trigger "comments_set_root_trigger"
  after insert on "public"."comments"
  for each row execute function "public"."comments_set_root"();

-- ============ Роль модератора ============

insert into public.roles (id, description)
values ('moderator', 'Moderates comments and user content')
on conflict (id) do nothing;

-- ============ RLS ============

create policy "Enable read access for all users" on "public"."comments"
  for select
  to public
  using (true);

create policy "Enable insert for authenticated users" on "public"."comments"
  for insert
  to "authenticated"
  with check (auth.uid() = author_id);

create policy "Enable delete for author or moderator" on "public"."comments"
  for delete
  to "authenticated"
  using (
    auth.uid() = author_id
    or exists (
      select 1
      from public.user_roles ur
      where ur.user_id = auth.uid()
        and ur.role_id in ('moderator', 'admin')
    )
  );

-- ============ RPC: выборки комментариев с данными автора ============
-- SECURITY DEFINER, т.к. auth.users недоступен анонимам напрямую.
-- Сам комментарий при этом доступен всем по RLS (SELECT для всех).

create or replace function "public"."get_map_roots"(
  p_layer integer,
  p_min_x integer,
  p_max_x integer,
  p_min_y integer,
  p_max_y integer
)
returns table (
  id               bigint,
  created_at       timestamp with time zone,
  updated_at       timestamp with time zone,
  author_id        uuid,
  author_name      text,
  author_avatar_url text,
  text             text,
  parent_id        bigint,
  root_id          bigint,
  block_id         bigint,
  map_x            double precision,
  map_y            double precision,
  layer            integer,
  expires_at       timestamp with time zone
)
language sql
stable
security definer
set search_path = 'public'
as $function$
  select
    c.id,
    c.created_at,
    c.updated_at,
    c.author_id,
    coalesce(
      nullif(au.raw_user_meta_data -> 'custom_claims' ->> 'global_name', ''),
      nullif(au.raw_user_meta_data ->> 'name', ''),
      nullif(au.raw_user_meta_data ->> 'full_name', ''),
      nullif(au.raw_user_meta_data ->> 'username', ''),
      au.email
    ) as author_name,
    nullif(au.raw_user_meta_data ->> 'avatar_url', '') as author_avatar_url,
    c.text,
    c.parent_id,
    c.root_id,
    c.block_id,
    c.map_x,
    c.map_y,
    c.layer,
    c.expires_at
  from public.comments c
  left join auth.users au on au.id = c.author_id
  where c.parent_id is null
    and c.block_id is null
    and c.layer = p_layer
    and c.map_x between p_min_x and p_max_x
    and c.map_y between p_min_y and p_max_y
    and (c.expires_at is null or c.expires_at > now())
  order by c.created_at asc;
$function$;

create or replace function "public"."get_block_comments"(
  p_block_id bigint
)
returns table (
  id               bigint,
  created_at       timestamp with time zone,
  updated_at       timestamp with time zone,
  author_id        uuid,
  author_name      text,
  author_avatar_url text,
  text             text,
  parent_id        bigint,
  root_id          bigint,
  block_id         bigint,
  map_x            double precision,
  map_y            double precision,
  layer            integer,
  expires_at       timestamp with time zone
)
language sql
stable
security definer
set search_path = 'public'
as $function$
  select
    c.id,
    c.created_at,
    c.updated_at,
    c.author_id,
    coalesce(
      nullif(au.raw_user_meta_data -> 'custom_claims' ->> 'global_name', ''),
      nullif(au.raw_user_meta_data ->> 'name', ''),
      nullif(au.raw_user_meta_data ->> 'full_name', ''),
      nullif(au.raw_user_meta_data ->> 'username', ''),
      au.email
    ) as author_name,
    nullif(au.raw_user_meta_data ->> 'avatar_url', '') as author_avatar_url,
    c.text,
    c.parent_id,
    c.root_id,
    c.block_id,
    c.map_x,
    c.map_y,
    c.layer,
    c.expires_at
  from public.comments c
  left join auth.users au on au.id = c.author_id
  -- Ответы (block_id = NULL) не наследуют местоположение, поэтому возвращаем
  -- весь тред корневых комментариев блока по root_id.
  where c.root_id in (
    select r.id
    from public.comments r
    where r.block_id = p_block_id
      and (r.expires_at is null or r.expires_at > now())
  )
    and (c.expires_at is null or c.expires_at > now())
  order by c.created_at asc;
$function$;

create or replace function "public"."get_comment_subtree"(
  p_root_id bigint
)
returns table (
  id               bigint,
  created_at       timestamp with time zone,
  updated_at       timestamp with time zone,
  author_id        uuid,
  author_name      text,
  author_avatar_url text,
  text             text,
  parent_id        bigint,
  root_id          bigint,
  block_id         bigint,
  map_x            double precision,
  map_y            double precision,
  layer            integer,
  expires_at       timestamp with time zone
)
language sql
stable
security definer
set search_path = 'public'
as $function$
  select
    c.id,
    c.created_at,
    c.updated_at,
    c.author_id,
    coalesce(
      nullif(au.raw_user_meta_data -> 'custom_claims' ->> 'global_name', ''),
      nullif(au.raw_user_meta_data ->> 'name', ''),
      nullif(au.raw_user_meta_data ->> 'full_name', ''),
      nullif(au.raw_user_meta_data ->> 'username', ''),
      au.email
    ) as author_name,
    nullif(au.raw_user_meta_data ->> 'avatar_url', '') as author_avatar_url,
    c.text,
    c.parent_id,
    c.root_id,
    c.block_id,
    c.map_x,
    c.map_y,
    c.layer,
    c.expires_at
  from public.comments c
  left join auth.users au on au.id = c.author_id
  where c.root_id = p_root_id
    and (c.expires_at is null or c.expires_at > now())
  order by c.created_at asc;
$function$;

-- ============ Storage: бакет для картинок комментариев ============

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'comment-images',
  'comment-images',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do nothing;

create policy "comment-images: public read" on storage.objects
  for select
  using (bucket_id = 'comment-images');

create policy "comment-images: authenticated insert" on storage.objects
  for insert
  to "authenticated"
  with check (bucket_id = 'comment-images');

create policy "comment-images: owner delete" on storage.objects
  for delete
  to "authenticated"
  using (bucket_id = 'comment-images' and owner_id = auth.uid()::text);

-- ============ Realtime и grants ============

alter publication "supabase_realtime" add table "public"."comments";

comment on table "public"."comments" is 'Comments on the map, on blocks, and replies to them';
comment on column "public"."comments"."root_id" is 'Top-level comment id of the thread (set by comments_set_root trigger)';
comment on column "public"."comments"."map_x" is 'X in block units (CELL_SIZE = 380 px); see map_y';
comment on column "public"."comments"."expires_at" is 'If set, the comment is temporary and hides after this time';

grant delete, insert, references, select, trigger, truncate, update on table "public"."comments" to "anon", "authenticated", "postgres", "service_role";

grant execute on function "public"."get_map_roots"(integer, integer, integer, integer, integer) to "anon", "authenticated", "postgres", "service_role";
grant execute on function "public"."get_block_comments"(bigint) to "anon", "authenticated", "postgres", "service_role";
grant execute on function "public"."get_comment_subtree"(bigint) to "anon", "authenticated", "postgres", "service_role";
grant execute on function "public"."comments_set_root"() to "postgres", "service_role";
